source 'https://rubygems.org'

gem 'chefspec'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'berkshelf'
gem 'stove'
gem 'rubocop'
gem 'rake'
gem 'foodcritic'
gem 'kitchen-digitalocean'
gem 'kitchen-dokken'
