name             'omnibus-gitlab'
maintainer       'GitLab Inc.'
maintainer_email 'marin@gitlab.com'
license          'All rights reserved'
description      'Installs/Configures GitLab using omnibus-gitlab'
long_description 'Installs/Configures GitLab using omnibus-gitlab'
version          '0.3.11'
issues_url       'https://gitlab.com/gitlab-org/cookbook-omnibus-gitlab/issues'
source_url       'https://gitlab.com/gitlab-org/cookbook-omnibus-gitlab/'

depends 'gitlab-vault'
depends 'apt'
