#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title PostReceive job statistics
graph_vlabel job time (s)
graph_args --base 1000 -l 0
graph_category gitlab
average.label Average PostReceive
pct90.label 90th-percentile PostReceive
graph_info The average and 90th-percentile value of the durations of the last 500 PostReceive jobs
EOM
        exit 0;;
esac

grep 'sidekiq:.* PostReceive .*done: .* sec$' /var/log/gitlab/sidekiq/current | tail -500 | awk '
{
  time[count] = $(NF - 1)
  total += time[count]
  count += 1
}
END {
  print "average.value " total/count
  asort(time)
  print "pct90.value " time[0.9*count]
}
'
