#!/bin/sh

case $1 in
   config)
        cat <<EOM
graph_title PostReceive job duration
graph_vlabel job time (s)
graph_args --base 1000 -l 0
graph_category gitlab
average.label Average PostReceive duration
pct90.label 90th-percentile PostReceive duration
graph_info The average and 90th-percentile value of the durations of the last ${window_size} PostReceive jobs
EOM
        exit 0;;
esac

# Variables m1, .., m5 contain date strings pointing to 1, .. 5 minutes ago
awk $(for m in $(seq 5); do echo "-vm$m=$(date +'%Y-%m-%dT%H:%M' --date="$m minute ago")"; done) '
($4 ~ m1 || $4 ~ m2  || $4 ~ m3 || $4 ~ m4 || $4 ~ m5) && /PostReceive.*done: .* sec$/ {
  time[count] = $(NF - 1)
  total += time[count]
  count += 1
}
END {
  if (count == 0) {
    print "average.value U"
    print "pct90.value U"
    exit 0
  }

  print "average.value " total/count
  asort(time)
  print "pct90.value " time[int(0.9*count)]
}
' /var/log/gitlab/sidekiq/current
