#!/bin/sh

case $1 in
  config)
    cat <<EOM
graph_title Unicorn worker age at memory restart
graph_vlabel avg worker age (s)
graph_args --base 1000 -l 0
graph_category gitlab
average.label Average Unicorn worker age when MemoryKiller kicks in
pct90.label 90th-percentile Unicorn worker age when MemoryKiller kicks in
graph_info The average and 90th-percentile value over the past 5 minutes of the age of Unicorn workers before the 'MemoryKiller' takes them.
EOM
    exit 0;;
esac

# Variables m1, .., m5 contain date strings pointing to 1, .. 5 minutes ago
awk $(for m in $(seq 5); do echo "-vm$m=$(date +'%Y-%m-%dT%H:%M' --date="$m minute ago")"; done) '
($2 ~ m1 || $2 ~ m2  || $2 ~ m3 || $2 ~ m4 || $2 ~ m5) && /Unicorn::WorkerKiller.*alive:/ {
  age[count] = $(NF - 3)
  total += age[count]
  count += 1
}
END {
  if (count == 0) {
    print "average.value U"
    print "pct90.value U"
    exit 0
  }

  print "average.value " total/count
  asort(age)
  print "pct90.value " age[int(0.9*count)]
}
' /var/log/gitlab/unicorn/unicorn_stderr.log
