#!/bin/sh

if [ -z "${window_size}" ] ; then
  window_size=100
fi

case $1 in
   config)
        cat <<EOM
graph_title PostReceive job duration
graph_vlabel job time (s)
graph_args --base 1000 -l 0
graph_category gitlab
average.label Average PostReceive duration
pct90.label 90th-percentile PostReceive duration
graph_info The average and 90th-percentile value of the durations of the last ${window_size} PostReceive jobs
EOM
        exit 0;;
esac

grep 'sidekiq:.* PostReceive .*done: .* sec$' /var/log/gitlab/sidekiq/current | tail -${window_size} | awk '
{
  time[count] = $(NF - 1)
  total += time[count]
  count += 1
}
END {
  print "average.value " total/count
  asort(time)
  print "pct90.value " time[0.9*count]
}
'
