#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Sidekiq memory use
graph_vlabel RSS (kB)
graph_args --base 1024 -l 0
graph_category gitlab
sidekiq_rss.label Sidekiq RSS
graph_info The Resident Set Size of the Sidekiq process managed by Runit for omnibus-gitlab.
EOM
        exit 0;;
esac

printf "sidekiq_rss.value "
awk '/VmRSS/ { print $2 }' /proc/$(cat /opt/gitlab/sv/sidekiq/supervise/pid)/status
